# Solving Systems of Linear Equations with Matrices

This notebook explains the concepts from the provided notes in a chronological order. We'll explore how matrices transform vectors and how to use the inverse of a matrix to solve systems of linear equations.

We will cover:
1. Representing simultaneous equations in matrix form (`Ax = b`).
2. Understanding the concept of an inverse matrix (`A⁻¹`) and the identity matrix (`I`).
3. Method 1: Using Gaussian Elimination to find a solution for a *specific* output.
4. Method 2: Using Gauss-Jordan Elimination to find the *general* inverse matrix (`A⁻¹`).

## 1. The Problem: Simultaneous Equations as Matrix Transformations

The key idea is that matrices can be seen as functions that transform vectors. When we have a system of simultaneous equations, we are trying to find an *input* vector that, after being transformed by a matrix, results in a given *output* vector.

Let's take the "Apples & Bananas" problem from the notes:

$2a + 3b = 8$

$10a + 1b = 13$

We can represent this in the form **Ax = b**, where:
- **A** is the transformation matrix.
- **x** is the input vector we want to find (the number of apples and bananas).
- **b** is the output vector.

In [4]:
import numpy as np

# The transformation matrix A
A = np.array([
    [2, 3],
    [10, 1]
])

# The output vector b
b = np.array([
    [8],
    [13]
])

print("Matrix A:\n", A)
print("\nVector b:\n", b)

Matrix A:
 [[ 2  3]
 [10  1]]

Vector b:
 [[ 8]
 [13]]


## 2. The Solution: Using the Inverse Matrix

To solve for our input vector `x`, we need to "undo" the transformation applied by matrix `A`. This is where the **inverse matrix**, denoted as **A⁻¹**, comes in.

The inverse matrix has a special property: when you multiply a matrix by its inverse, you get the **identity matrix (I)**.

> **A⁻¹A = I**

The identity matrix is the matrix equivalent of the number 1; it doesn't change a vector when multiplied. For a 2x2 matrix, `I` is:

```
[[1, 0],
 [0, 1]]
```

By multiplying both sides of our original equation `Ax = b` by `A⁻¹`, we can isolate `x`:

> **A⁻¹(Ax) = A⁻¹b**
> **(A⁻¹A)x = A⁻¹b**
> **Ix = A⁻¹b**
> **x = A⁻¹b**

So, if we can find the inverse of `A`, we can find our input vector `x`.

## 3. Method 1: Gaussian Elimination for a Specific Output

This method solves the system for a single, specific output `b` without calculating the full inverse. We combine `A` and `b` into an **augmented matrix** `[A|b]` and perform row operations to get it into **echelon form** (an upper triangular matrix).

Let's use the other example from your notes:

**A** = `[[1, 1, 3], [1, 2, 4], [1, 1, 2]]`

**b** = `[[15], [21], [13]]`

Our augmented matrix is:
`[[1, 1, 3 | 15], [1, 2, 4 | 21], [1, 1, 2 | 13]]`

**Step 1: Take row 1 from row 2 and row 3.**
- R2 = R2 - R1
- R3 = R3 - R1

This results in:
`[[1, 1, 3 | 15], [0, 1, 1 | 6], [0, 0, -1 | -2]]`

Now the matrix is in echelon form. We can solve for `c` from the last row:
- `-1c = -2  => c = 2`

Then we use **back substitution** to find `b` and `a`.
- `b + c = 6  => b + 2 = 6  => b = 4`
- `a + b + 3c = 15  => a + 4 + 3(2) = 15  => a + 10 = 15  => a = 5`

So, our solution vector `x` is `[5, 4, 2]`.

In [5]:
# We can verify this solution with NumPy's solver
A_ex = np.array([
    [1, 1, 3],
    [1, 2, 4],
    [1, 1, 2]
])

b_ex = np.array([
    [15],
    [21],
    [13]
])

# Use np.linalg.solve to find x
x_solution = np.linalg.solve(A_ex, b_ex)
print("The solution vector x is:\n", x_solution)

The solution vector x is:
 [[5.]
 [4.]
 [2.]]


## 4. Method 2: Gauss-Jordan Elimination to Find the Inverse

This is a more powerful method because it finds the actual inverse matrix `A⁻¹`, which allows us to find the solution `x` for *any* output vector `b`.

The process is to augment matrix `A` with the **identity matrix `I`**, forming `[A|I]`. We then perform row operations on the entire augmented matrix until the left side (`A`) becomes the identity matrix. The right side will then be the inverse, `A⁻¹`.

> **[A | I]  →  [I | A⁻¹]**

Let's use the same matrix `A`:
`A = [[1, 1, 3], [1, 2, 4], [1, 1, 2]]`

**Start:** `[[1, 1, 3 | 1, 0, 0], [1, 2, 4 | 0, 1, 0], [1, 1, 2 | 0, 0, 1]]`

**Step 1: Subtract Row 1 from Row 2 and Row 3**
`[[1, 1, 3 | 1, 0, 0], [0, 1, 1 | -1, 1, 0], [0, 0, -1 | -1, 0, 1]]`

**Step 2: Multiply Row 3 by -1**
`[[1, 1, 3 | 1, 0, 0], [0, 1, 1 | -1, 1, 0], [0, 0, 1 | 1, 0, -1]]`

Now we work backwards (this is the "Jordan" part of the method).

**Step 3: Subtract Row 3 from Row 2. Subtract 3 * Row 3 from Row 1.**
`[[1, 1, 0 | -2, 0, 3], [0, 1, 0 | -2, 1, 1], [0, 0, 1 | 1, 0, -1]]`

**Step 4: Subtract Row 2 from Row 1.**
`[[1, 0, 0 | 0, -1, 2], [0, 1, 0 | -2, 1, 1], [0, 0, 1 | 1, 0, -1]]`

We have successfully transformed the left side to the identity matrix. The right side is now our inverse matrix!

**A⁻¹** = `[[0, -1, 2], [-2, 1, 1], [1, 0, -1]]`

In [6]:
# Let's verify this with NumPy's inverse function
A_inv = np.linalg.inv(A_ex)

print("The inverse of A is:\n", A_inv)

# Now, we can solve for x using x = A⁻¹b
x_from_inverse = A_inv @ b_ex # The @ symbol is for matrix multiplication

print("\nThe solution x found using the inverse is:\n", x_from_inverse)

The inverse of A is:
 [[ 0. -1.  2.]
 [-2.  1.  1.]
 [ 1. -0. -1.]]

The solution x found using the inverse is:
 [[5.]
 [4.]
 [2.]]


## Conclusion

As we've seen, we can solve a system of linear equations `Ax = b` in two main ways:

1.  **Gaussian Elimination (`[A|b]`)**: This is efficient if you only need to solve for one specific output `b`. It transforms `A` into an upper-triangular matrix and uses back-substitution.

2.  **Gauss-Jordan Elimination (`[A|I]`)**: This is more versatile as it finds the complete inverse `A⁻¹`. Once you have the inverse, you can easily find the solution `x` for *any* output `b` by simply performing the matrix multiplication `x = A⁻¹b`.