# Matrices for Changing Basis

This notebook explains how to transform a vector's coordinates from one basis to another. We'll explore two scenarios:

1.  Transforming a vector from a custom basis (we'll call it "Bear's Basis") to our standard basis.
2.  Transforming a vector from our standard basis to "Bear's Basis".

## Setting up the Bases

Our standard basis (let's call it "My Basis") is defined by the vectors $\hat{i} = \begin{bmatrix} 1 \\ 0 \end{bmatrix}$ and $\hat{j} = \begin{bmatrix} 0 \\ 1 \end{bmatrix}$.

Let's define a new basis, "Bear's Basis", using two different basis vectors, $\vec{b_1}$ and $\vec{b_2}$. These vectors are described using the coordinates of our standard basis.

$$ \vec{b_1} = \begin{bmatrix} 3 \\ 1 \end{bmatrix}, \quad \vec{b_2} = \begin{bmatrix} 1 \\ 1 \end{bmatrix} $$

We can represent this new basis as a single **transformation matrix**, $B$, where the columns are the basis vectors of Bear's world.

In [3]:
import numpy as np

# Bear's transformation matrix
# The columns are the basis vectors of Bear's basis.
B = np.array([
    [3, 1],
    [1, 1]
])

print("Bear's transformation matrix B:")
print(B)

Bear's transformation matrix B:
[[3 1]
 [1 1]]


## 1. From Bear's Basis to My Basis

Imagine we have a vector whose coordinates are given in Bear's basis. Let's call this vector $\vec{v}_{Bear}$.

$$ \vec{v}_{Bear} = \begin{bmatrix} 3/2 \\ 1/2 \end{bmatrix} $$

This means the vector is a linear combination of Bear's basis vectors: $ (3/2) \cdot \vec{b_1} + (1/2) \cdot \vec{b_2} $.

To find the coordinates of this vector in our standard basis (My Basis), we simply multiply the transformation matrix $B$ by the vector $\vec{v}_{Bear}$.

In [4]:
# A vector in Bear's basis
v_bear = np.array([[1.5], [0.5]]) # Using 3/2 = 1.5 and 1/2 = 0.5

# To transform from Bear's basis to my basis, we multiply B * v_bear
v_my = B @ v_bear

print("Vector in Bear's basis:")
print(v_bear)
print("\nSame vector in My (standard) basis:")
print(v_my)

Vector in Bear's basis:
[[1.5]
 [0.5]]

Same vector in My (standard) basis:
[[5.]
 [2.]]


The result is $\begin{bmatrix} 5 \\ 2 \end{bmatrix}$. So, a vector with coordinates $\begin{bmatrix} 1.5 \\ 0.5 \end{bmatrix}$ in Bear's world has coordinates $\begin{bmatrix} 5 \\ 2 \end{bmatrix}$ in our standard world.

$$ \begin{bmatrix} 3 & 1 \\ 1 & 1 \end{bmatrix} \begin{bmatrix} 3/2 \\ 1/2 \end{bmatrix} = \begin{bmatrix} 3(3/2) + 1(1/2) \\ 1(3/2) + 1(1/2) \end{bmatrix} = \begin{bmatrix} 9/2 + 1/2 \\ 3/2 + 1/2 \end{bmatrix} = \begin{bmatrix} 10/2 \\ 4/2 \end{bmatrix} = \begin{bmatrix} 5 \\ 2 \end{bmatrix} $$

## 2. From My Basis to Bear's Basis

More often, we have a vector in our standard basis and want to find its coordinates in a different basis. This is the reverse process.

We just showed that:
$$ B \cdot \vec{v}_{Bear} = \vec{v}_{My} $$

To solve for $\vec{v}_{Bear}$, we need to multiply by the **inverse** of the transformation matrix, $B^{-1}$.

$$ \vec{v}_{Bear} = B^{-1} \cdot \vec{v}_{My} $$

First, let's find the inverse of $B = \begin{bmatrix} a & b \\ c & d \end{bmatrix} = \begin{bmatrix} 3 & 1 \\ 1 & 1 \end{bmatrix}$.
The formula for the inverse of a 2x2 matrix is:
$$ B^{-1} = \frac{1}{ad-bc} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix} $$

The determinant is $ad-bc = (3)(1) - (1)(1) = 2$. So the inverse is:

$$ B^{-1} = \frac{1}{2} \begin{bmatrix} 1 & -1 \\ -1 & 3 \end{bmatrix} $$

In [5]:
# Calculate the inverse of B using numpy
B_inv = np.linalg.inv(B)

print("Inverse of B:")
print(B_inv)

Inverse of B:
[[ 0.5 -0.5]
 [-0.5  1.5]]


Now we can transform the vector $\vec{v}_{My} = \begin{bmatrix} 5 \\ 2 \end{bmatrix}$ from our basis into Bear's basis by multiplying it by $B^{-1}$.

In [6]:
# The vector in My (standard) basis
v_my = np.array([[5], [2]])

# To transform from my basis to Bear's, we multiply B_inv * v_my
v_bear_calculated = B_inv @ v_my

print("Vector in My (standard) basis:")
print(v_my)
print("\nSame vector in Bear's basis:")
print(v_bear_calculated)

Vector in My (standard) basis:
[[5]
 [2]]

Same vector in Bear's basis:
[[1.5]
 [0.5]]


As expected, we get back the original vector $\begin{bmatrix} 1.5 \\ 0.5 \end{bmatrix}$. This confirms that a vector with coordinates $\begin{bmatrix} 5 \\ 2 \end{bmatrix}$ in our standard world is represented by the coordinates $\begin{bmatrix} 1.5 \\ 0.5 \end{bmatrix}$ in Bear's world.