# Transforming a Vector in a Changed Basis basis

This notebook explains how to apply a transformation (like a rotation) to a vector that is defined in a non-standard coordinate system or basis.

## The Problem Setup

Let's define a non-standard basis, which we'll call "Bear's Basis". This basis is represented by the matrix $B$, where the columns are the basis vectors.

Bear's Basis: $B = \begin{bmatrix} 3 & 1 \\ 1 & 1 \end{bmatrix}$

Now, consider a vector $v$ whose coordinates are given in Bear's Basis.

Vector in Bear's Basis: $v_B = \begin{bmatrix} x \\ y \end{bmatrix}$

Our goal is to **rotate this vector $v$ by 45° counter-clockwise**.

The challenge is that the standard 45° rotation matrix is designed to work on vectors in the standard basis (our system), not in Bear's Basis. We don't immediately know how to write a rotation matrix that works directly in Bear's coordinate system.

## The Strategy: A Three-Step Process

The solution is to temporarily convert the vector to our standard basis, perform the rotation there, and then convert it back to Bear's basis.

Here is the standard 45° counter-clockwise rotation matrix, $R_{45}$:

$R_{45} = \begin{bmatrix} \cos(45°) & -\sin(45°) \\ \sin(45°) & \cos(45°) \end{bmatrix} = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & -1 \\ 1 & 1 \end{bmatrix}$

### Step 1: Change the vector to our coordinate frame (Standard Basis)

To see what the vector $v_B$ looks like in the standard basis, we multiply it by the basis matrix $B$. Let's call the resulting vector $v_{std}$.

$v_{std} = B \cdot v_B = \begin{bmatrix} 3 & 1 \\ 1 & 1 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix}$

### Step 2: Apply the rotation in our basis

Now that the vector is in the standard basis, we can apply the standard rotation matrix $R_{45}$ to it.

$v'_{std} = R_{45} \cdot v_{std} = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & -1 \\ 1 & 1 \end{bmatrix} \left( \begin{bmatrix} 3 & 1 \\ 1 & 1 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} \right)$

### Step 3: Transform the resulting vector back into Bear's basis

The vector $v'_{std}$ is the rotated vector, but its coordinates are in our standard basis. To find the coordinates in Bear's basis, we need to "undo" the change of basis from Step 1. We do this by multiplying by the inverse of the basis matrix, $B^{-1}$.

$v'_B = B^{-1} \cdot v'_{std} = B^{-1} R_{45} B v_B$

Let's find $B^{-1}$:
$\det(B) = (3)(1) - (1)(1) = 2$
$B^{-1} = \frac{1}{2} \begin{bmatrix} 1 & -1 \\ -1 & 3 \end{bmatrix}$

So, the complete operation is:

$v'_B = \underbrace{\frac{1}{2}\begin{bmatrix} 1 & -1 \\ -1 & 3 \end{bmatrix}}_{B^{-1}} \underbrace{\frac{1}{\sqrt{2}}\begin{bmatrix} 1 & -1 \\ 1 & 1 \end{bmatrix}}_{R_{45}} \underbrace{\begin{bmatrix} 3 & 1 \\ 1 & 1 \end{bmatrix}}_{B} \underbrace{\begin{bmatrix} x \\ y \end{bmatrix}}_{v_B}$

## The Transformation Matrix in the New Basis

The combination $B^{-1}RB$ gives us a new matrix, let's call it $R_B$, which is the 45° rotation operator *as seen from within Bear's basis*.

$$ R_B = B^{-1} R_{45} B $$

Applying this new matrix $R_B$ to a vector $v_B$ (in Bear's basis) will give the rotated vector $v'_B$ (also in Bear's basis).

$$ v'_B = R_B v_B $$

## Python Implementation

In [4]:
import numpy as np

# Define the Bear's Basis matrix B
B = np.array([
    [3, 1],
    [1, 1]
])

# Define the standard 45-degree rotation matrix R_45
R_45 = (1/np.sqrt(2)) * np.array([
    [1, -1],
    [1, 1]
])

# Calculate the inverse of B
B_inv = np.linalg.inv(B)

# Let's take an example vector in Bear's basis.
# Let's say v_B = [1, 0]. This corresponds to the first basis vector of B.
v_B = np.array([1, 0])

print(f"Bear's Basis (B):\n{B}\n")
print(f"Standard 45° Rotation (R_45):\n{R_45}\n")
print(f"Inverse of Bear's Basis (B_inv):\n{B_inv}\n")
print(f"Original vector in Bear's basis (v_B): {v_B}\n")

Bear's Basis (B):
[[3 1]
 [1 1]]

Standard 45° Rotation (R_45):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Inverse of Bear's Basis (B_inv):
[[ 0.5 -0.5]
 [-0.5  1.5]]

Original vector in Bear's basis (v_B): [1 0]



In [5]:
# STEP 1: Convert v_B to the standard basis
v_std = B @ v_B
print(f"Step 1: v_B in standard basis (v_std): {v_std}\n")

# STEP 2: Apply the rotation in the standard basis
v_std_rotated = R_45 @ v_std
print(f"Step 2: Rotated vector in standard basis (v_std_rotated): {v_std_rotated}\n")

# STEP 3: Convert the rotated vector back to Bear's basis
v_B_rotated = B_inv @ v_std_rotated
print(f"Step 3: Final rotated vector in Bear's basis (v_B_rotated): {v_B_rotated}\n")

Step 1: v_B in standard basis (v_std): [3 1]

Step 2: Rotated vector in standard basis (v_std_rotated): [1.41421356 2.82842712]

Step 3: Final rotated vector in Bear's basis (v_B_rotated): [-0.70710678  3.53553391]



### Using the Combined Transformation Matrix

We can also compute the single matrix $R_B$ that performs the rotation directly in Bear's basis and apply it.

In [6]:
# Calculate the rotation matrix for Bear's basis
R_B = B_inv @ R_45 @ B

print(f"The 45° rotation matrix in Bear's basis (R_B):\n{R_B}\n")

# Apply this new operator directly to the original vector v_B
v_B_rotated_direct = R_B @ v_B

print(f"Final rotated vector calculated directly (R_B @ v_B): {v_B_rotated_direct}")

# Check if the results are the same (they should be)
print(f"Are the results from both methods close? {np.allclose(v_B_rotated, v_B_rotated_direct)}")

The 45° rotation matrix in Bear's basis (R_B):
[[-0.70710678 -0.70710678]
 [ 3.53553391  2.12132034]]

Final rotated vector calculated directly (R_B @ v_B): [-0.70710678  3.53553391]
Are the results from both methods close? True
