# Understanding Orthogonal & Orthonormal Matrices

This notebook covers the key concepts of orthogonal and orthonormal matrices. We'll explore their definition, properties, and why they are so useful in linear algebra.

## 1. What is an Orthogonal Matrix?

An **orthogonal matrix** is a square matrix whose columns (and rows) form an *orthonormal set* of vectors. 

This means the matrix can be seen as a transformation matrix where the column vectors define a new basis. In this new basis, all basis vectors are perpendicular to each other and have a length of 1.

## 2. The Orthonormal Basis Set

A set of vectors is called an **orthonormal basis set** if it satisfies two conditions:

1.  **Orthogonality**: All vectors in the set are mutually perpendicular. The dot product of any two different vectors is 0.
    $$ a_i \cdot a_j = 0 \quad \text{if } i \neq j $$

2.  **Normalization**: Each vector in the set has a unit length (a magnitude of 1). The dot product of any vector with itself is 1.
    $$ a_i \cdot a_j = 1 \quad \text{if } i = j $$

## 3. The Defining Property: $A^T A = I$

The most important property of an orthogonal matrix $A$ arises when you multiply it by its transpose, $A^T$. 

Let the matrix $A$ be composed of column vectors $a_1, a_2, \dots, a_n$:
$$ A = \begin{pmatrix} | & | & & | \\ a_1 & a_2 & \cdots & a_n \\ | & | & & | \end{pmatrix} $$

Then its transpose, $A^T$, has these vectors as its rows:
$$ A^T = \begin{pmatrix} - & a_1 & - \\ - & a_2 & - \\ & \vdots & \\ - & a_n & - \end{pmatrix} $$

When we compute the product $A^T A$, the element at position $(i, j)$ is the dot product of the $i$-th row of $A^T$ (which is $a_i$) and the $j$-th column of $A$ (which is $a_j$).

$$ A^T A = \begin{pmatrix} a_1 \cdot a_1 & a_1 \cdot a_2 & \cdots & a_1 \cdot a_n \\ a_2 \cdot a_1 & a_2 \cdot a_2 & \cdots & a_2 \cdot a_n \\ \vdots & \vdots & \ddots & \vdots \\ a_n \cdot a_1 & a_n \cdot a_2 & \cdots & a_n \cdot a_n \end{pmatrix} = \begin{pmatrix} 1 & 0 & \cdots & 0 \\ 0 & 1 & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \cdots & 1 \end{pmatrix} = I $$

This happens because the column vectors form an orthonormal set.

## 4. A Powerful Shortcut: The Inverse

From the property $A^T A = I$, we can see that the transpose of an orthogonal matrix is also its inverse.

$$ A^T = A^{-1} $$

This is incredibly useful because calculating the transpose is computationally trivial, while finding the inverse of a general matrix is very expensive. For an orthogonal matrix, this difficult task becomes easy.

The inverse of a matrix performs the reverse transformation. So, for an orthogonal matrix, its **transpose performs the reverse transformation**.

In [1]:
import numpy as np

# Let's create a 2D rotation matrix, which is a classic example of an orthogonal matrix.
theta = np.pi / 4  # 45 degrees
A = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta), np.cos(theta)]
])

print("Orthogonal Matrix A:\n", A)

# Let's verify the property A^T * A = I
A_transpose = A.T
identity_matrix = A_transpose @ A # Using @ for matrix multiplication

print("\nTranspose of A (A^T):\n", A_transpose)
print("\nProduct A^T * A:\n", np.round(identity_matrix)) # Rounding to handle floating point inaccuracies

# Now let's compare the transpose with the inverse calculated by NumPy
A_inverse = np.linalg.inv(A)

print("\nInverse of A (A^-1) from np.linalg.inv:\n", A_inverse)
print("\nIs A^T equal to A^-1?", np.allclose(A_transpose, A_inverse))

Orthogonal Matrix A:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Transpose of A (A^T):
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Product A^T * A:
 [[ 1. -0.]
 [-0.  1.]]

Inverse of A (A^-1) from np.linalg.inv:
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Is A^T equal to A^-1? True


## 5. Key Properties Summary

1.  **Inverse is the Transpose**: As shown above, $A^T = A^{-1}$.
2.  **Determinant is $\pm 1$**: The determinant of an orthogonal matrix is always either +1 (for a pure rotation) or -1 (for a reflection).
3.  **Projection is just the dot product**: Projecting a vector onto one of the basis vectors of an orthonormal set is simplified to just calculating their dot product.

In [2]:
# Let's calculate the determinant of our matrix A
det_A = np.linalg.det(A)
print(f"The determinant of A is: {det_A:.2f}")

The determinant of A is: 1.00
